/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiCompetitionsRouteImport } from './routes/api/competitions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPluginsRouteImport } from './routes/api/plugins'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors/$authorId'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins/$pluginId'
import { Route as ApiAdminCompetitionsRouteImport } from './routes/api/admin/competitions'
import { Route as ApiAdminExplorerPollRouteImport } from './routes/api/admin/explorer-poll'
import { Route as ApiAdminLightPollRouteImport } from './routes/api/admin/light-poll'
import { Route as ApiAdminPlacementsRouteImport } from './routes/api/admin/placements'
import { Route as ApiAdminSnapshotRouteImport } from './routes/api/admin/snapshot'
import { Route as ApiAuthorsAuthorIdRouteImport } from './routes/api/authors/$authorId'
import { Route as ApiAuthorsLeaderboardRouteImport } from './routes/api/authors/leaderboard'
import { Route as ApiHealthBrokenRouteImport } from './routes/api/health/broken'
import { Route as ApiHealthUnverifiedRouteImport } from './routes/api/health/unverified'
import { Route as ApiLeaderboardMetricRouteImport } from './routes/api/leaderboard/$metric'
import { Route as ApiLeaderboardTrendingRouteImport } from './routes/api/leaderboard/trending'
import { Route as ApiPluginsIdRouteImport } from './routes/api/plugins/$id'
import { Route as ApiStatsBreakdownRouteImport } from './routes/api/stats/breakdown'
import { Route as ApiStatsCategoriesRouteImport } from './routes/api/stats/categories'
import { Route as ApiStatsHeatmapRouteImport } from './routes/api/stats/heatmap'
import { Route as ApiStatsPublishedRouteImport } from './routes/api/stats/published'
import { Route as ApiStatsUpdatedRouteImport } from './routes/api/stats/updated'
import { Route as ApiStatsVerifiedRouteImport } from './routes/api/stats/verified'
import { Route as OgPluginsIdRouteImport } from './routes/og/plugins/$id'
import { Route as ApiBadgesStatIdRouteImport } from './routes/api/badges/$stat/$id'
import { Route as ApiBadgesWinnerIdRouteImport } from './routes/api/badges/winner/$id'
import { Route as ApiChartsOmagraphKindRouteImport } from './routes/api/charts/omagraph/$kind'
import { Route as ApiBadgesRankingStatIdRouteImport } from './routes/api/badges/ranking/$stat/$id'
import { Route as ApiChartsAuthorLoginMetricRouteImport } from './routes/api/charts/author/$login/$metric'
import { Route as ApiChartsPluginIdMetricRouteImport } from './routes/api/charts/plugin/$id/$metric'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitionsRoute = ApiCompetitionsRouteImport.update({
  id: '/api/competitions',
  path: '/api/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsRoute = ApiPluginsRouteImport.update({
  id: '/api/plugins',
  path: '/api/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCompetitionsRoute = ApiAdminCompetitionsRouteImport.update({
  id: '/api/admin/competitions',
  path: '/api/admin/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExplorerPollRoute = ApiAdminExplorerPollRouteImport.update({
  id: '/api/admin/explorer-poll',
  path: '/api/admin/explorer-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLightPollRoute = ApiAdminLightPollRouteImport.update({
  id: '/api/admin/light-poll',
  path: '/api/admin/light-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlacementsRoute = ApiAdminPlacementsRouteImport.update({
  id: '/api/admin/placements',
  path: '/api/admin/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSnapshotRoute = ApiAdminSnapshotRouteImport.update({
  id: '/api/admin/snapshot',
  path: '/api/admin/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsAuthorIdRoute = ApiAuthorsAuthorIdRouteImport.update({
  id: '/api/authors/$authorId',
  path: '/api/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsLeaderboardRoute = ApiAuthorsLeaderboardRouteImport.update({
  id: '/api/authors/leaderboard',
  path: '/api/authors/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthBrokenRoute = ApiHealthBrokenRouteImport.update({
  id: '/broken',
  path: '/broken',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthUnverifiedRoute = ApiHealthUnverifiedRouteImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiLeaderboardMetricRoute = ApiLeaderboardMetricRouteImport.update({
  id: '/api/leaderboard/$metric',
  path: '/api/leaderboard/$metric',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardTrendingRoute = ApiLeaderboardTrendingRouteImport.update({
  id: '/api/leaderboard/trending',
  path: '/api/leaderboard/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsIdRoute = ApiPluginsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPluginsRoute,
} as any)
const ApiStatsBreakdownRoute = ApiStatsBreakdownRouteImport.update({
  id: '/api/stats/breakdown',
  path: '/api/stats/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsCategoriesRoute = ApiStatsCategoriesRouteImport.update({
  id: '/api/stats/categories',
  path: '/api/stats/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsHeatmapRoute = ApiStatsHeatmapRouteImport.update({
  id: '/api/stats/heatmap',
  path: '/api/stats/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsPublishedRoute = ApiStatsPublishedRouteImport.update({
  id: '/api/stats/published',
  path: '/api/stats/published',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsUpdatedRoute = ApiStatsUpdatedRouteImport.update({
  id: '/api/stats/updated',
  path: '/api/stats/updated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsVerifiedRoute = ApiStatsVerifiedRouteImport.update({
  id: '/api/stats/verified',
  path: '/api/stats/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPluginsIdRoute = OgPluginsIdRouteImport.update({
  id: '/og/plugins/$id',
  path: '/og/plugins/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgesStatIdRoute = ApiBadgesStatIdRouteImport.update({
  id: '/api/badges/$stat/$id',
  path: '/api/badges/$stat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgesWinnerIdRoute = ApiBadgesWinnerIdRouteImport.update({
  id: '/api/badges/winner/$id',
  path: '/api/badges/winner/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsOmagraphKindRoute = ApiChartsOmagraphKindRouteImport.update({
  id: '/api/charts/omagraph/$kind',
  path: '/api/charts/omagraph/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgesRankingStatIdRoute = ApiBadgesRankingStatIdRouteImport.update({
  id: '/api/badges/ranking/$stat/$id',
  path: '/api/badges/ranking/$stat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsAuthorLoginMetricRoute =
  ApiChartsAuthorLoginMetricRouteImport.update({
    id: '/api/charts/author/$login/$metric',
    path: '/api/charts/author/$login/$metric',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChartsPluginIdMetricRoute = ApiChartsPluginIdMetricRouteImport.update({
  id: '/api/charts/plugin/$id/$metric',
  path: '/api/charts/plugin/$id/$metric',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/charts': typeof ChartsRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/plugins': typeof ApiPluginsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/api/admin/competitions': typeof ApiAdminCompetitionsRoute
  '/api/admin/explorer-poll': typeof ApiAdminExplorerPollRoute
  '/api/admin/light-poll': typeof ApiAdminLightPollRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/snapshot': typeof ApiAdminSnapshotRoute
  '/api/authors/$authorId': typeof ApiAuthorsAuthorIdRoute
  '/api/authors/leaderboard': typeof ApiAuthorsLeaderboardRoute
  '/api/health/broken': typeof ApiHealthBrokenRoute
  '/api/health/unverified': typeof ApiHealthUnverifiedRoute
  '/api/leaderboard/$metric': typeof ApiLeaderboardMetricRoute
  '/api/leaderboard/trending': typeof ApiLeaderboardTrendingRoute
  '/api/plugins/$id': typeof ApiPluginsIdRoute
  '/api/stats/breakdown': typeof ApiStatsBreakdownRoute
  '/api/stats/categories': typeof ApiStatsCategoriesRoute
  '/api/stats/heatmap': typeof ApiStatsHeatmapRoute
  '/api/stats/published': typeof ApiStatsPublishedRoute
  '/api/stats/updated': typeof ApiStatsUpdatedRoute
  '/api/stats/verified': typeof ApiStatsVerifiedRoute
  '/og/plugins/$id': typeof OgPluginsIdRoute
  '/api/badges/$stat/$id': typeof ApiBadgesStatIdRoute
  '/api/badges/winner/$id': typeof ApiBadgesWinnerIdRoute
  '/api/charts/omagraph/$kind': typeof ApiChartsOmagraphKindRoute
  '/api/badges/ranking/$stat/$id': typeof ApiBadgesRankingStatIdRoute
  '/api/charts/author/$login/$metric': typeof ApiChartsAuthorLoginMetricRoute
  '/api/charts/plugin/$id/$metric': typeof ApiChartsPluginIdMetricRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/charts': typeof ChartsRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/plugins': typeof ApiPluginsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/api/admin/competitions': typeof ApiAdminCompetitionsRoute
  '/api/admin/explorer-poll': typeof ApiAdminExplorerPollRoute
  '/api/admin/light-poll': typeof ApiAdminLightPollRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/snapshot': typeof ApiAdminSnapshotRoute
  '/api/authors/$authorId': typeof ApiAuthorsAuthorIdRoute
  '/api/authors/leaderboard': typeof ApiAuthorsLeaderboardRoute
  '/api/health/broken': typeof ApiHealthBrokenRoute
  '/api/health/unverified': typeof ApiHealthUnverifiedRoute
  '/api/leaderboard/$metric': typeof ApiLeaderboardMetricRoute
  '/api/leaderboard/trending': typeof ApiLeaderboardTrendingRoute
  '/api/plugins/$id': typeof ApiPluginsIdRoute
  '/api/stats/breakdown': typeof ApiStatsBreakdownRoute
  '/api/stats/categories': typeof ApiStatsCategoriesRoute
  '/api/stats/heatmap': typeof ApiStatsHeatmapRoute
  '/api/stats/published': typeof ApiStatsPublishedRoute
  '/api/stats/updated': typeof ApiStatsUpdatedRoute
  '/api/stats/verified': typeof ApiStatsVerifiedRoute
  '/og/plugins/$id': typeof OgPluginsIdRoute
  '/api/badges/$stat/$id': typeof ApiBadgesStatIdRoute
  '/api/badges/winner/$id': typeof ApiBadgesWinnerIdRoute
  '/api/charts/omagraph/$kind': typeof ApiChartsOmagraphKindRoute
  '/api/badges/ranking/$stat/$id': typeof ApiBadgesRankingStatIdRoute
  '/api/charts/author/$login/$metric': typeof ApiChartsAuthorLoginMetricRoute
  '/api/charts/plugin/$id/$metric': typeof ApiChartsPluginIdMetricRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/charts': typeof ChartsRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/competitions': typeof ApiCompetitionsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/plugins': typeof ApiPluginsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/api/admin/competitions': typeof ApiAdminCompetitionsRoute
  '/api/admin/explorer-poll': typeof ApiAdminExplorerPollRoute
  '/api/admin/light-poll': typeof ApiAdminLightPollRoute
  '/api/admin/placements': typeof ApiAdminPlacementsRoute
  '/api/admin/snapshot': typeof ApiAdminSnapshotRoute
  '/api/authors/$authorId': typeof ApiAuthorsAuthorIdRoute
  '/api/authors/leaderboard': typeof ApiAuthorsLeaderboardRoute
  '/api/health/broken': typeof ApiHealthBrokenRoute
  '/api/health/unverified': typeof ApiHealthUnverifiedRoute
  '/api/leaderboard/$metric': typeof ApiLeaderboardMetricRoute
  '/api/leaderboard/trending': typeof ApiLeaderboardTrendingRoute
  '/api/plugins/$id': typeof ApiPluginsIdRoute
  '/api/stats/breakdown': typeof ApiStatsBreakdownRoute
  '/api/stats/categories': typeof ApiStatsCategoriesRoute
  '/api/stats/heatmap': typeof ApiStatsHeatmapRoute
  '/api/stats/published': typeof ApiStatsPublishedRoute
  '/api/stats/updated': typeof ApiStatsUpdatedRoute
  '/api/stats/verified': typeof ApiStatsVerifiedRoute
  '/og/plugins/$id': typeof OgPluginsIdRoute
  '/api/badges/$stat/$id': typeof ApiBadgesStatIdRoute
  '/api/badges/winner/$id': typeof ApiBadgesWinnerIdRoute
  '/api/charts/omagraph/$kind': typeof ApiChartsOmagraphKindRoute
  '/api/badges/ranking/$stat/$id': typeof ApiBadgesRankingStatIdRoute
  '/api/charts/author/$login/$metric': typeof ApiChartsAuthorLoginMetricRoute
  '/api/charts/plugin/$id/$metric': typeof ApiChartsPluginIdMetricRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api-docs'
    | '/badges'
    | '/categories'
    | '/charts'
    | '/competitions'
    | '/health'
    | '/leaderboards'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/competitions'
    | '/api/health'
    | '/api/plugins'
    | '/api/search'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
    | '/api/admin/competitions'
    | '/api/admin/explorer-poll'
    | '/api/admin/light-poll'
    | '/api/admin/placements'
    | '/api/admin/snapshot'
    | '/api/authors/$authorId'
    | '/api/authors/leaderboard'
    | '/api/health/broken'
    | '/api/health/unverified'
    | '/api/leaderboard/$metric'
    | '/api/leaderboard/trending'
    | '/api/plugins/$id'
    | '/api/stats/breakdown'
    | '/api/stats/categories'
    | '/api/stats/heatmap'
    | '/api/stats/published'
    | '/api/stats/updated'
    | '/api/stats/verified'
    | '/og/plugins/$id'
    | '/api/badges/$stat/$id'
    | '/api/badges/winner/$id'
    | '/api/charts/omagraph/$kind'
    | '/api/badges/ranking/$stat/$id'
    | '/api/charts/author/$login/$metric'
    | '/api/charts/plugin/$id/$metric'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/api-docs'
    | '/badges'
    | '/categories'
    | '/charts'
    | '/competitions'
    | '/health'
    | '/leaderboards'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/competitions'
    | '/api/health'
    | '/api/plugins'
    | '/api/search'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
    | '/api/admin/competitions'
    | '/api/admin/explorer-poll'
    | '/api/admin/light-poll'
    | '/api/admin/placements'
    | '/api/admin/snapshot'
    | '/api/authors/$authorId'
    | '/api/authors/leaderboard'
    | '/api/health/broken'
    | '/api/health/unverified'
    | '/api/leaderboard/$metric'
    | '/api/leaderboard/trending'
    | '/api/plugins/$id'
    | '/api/stats/breakdown'
    | '/api/stats/categories'
    | '/api/stats/heatmap'
    | '/api/stats/published'
    | '/api/stats/updated'
    | '/api/stats/verified'
    | '/og/plugins/$id'
    | '/api/badges/$stat/$id'
    | '/api/badges/winner/$id'
    | '/api/charts/omagraph/$kind'
    | '/api/badges/ranking/$stat/$id'
    | '/api/charts/author/$login/$metric'
    | '/api/charts/plugin/$id/$metric'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api-docs'
    | '/badges'
    | '/categories'
    | '/charts'
    | '/competitions'
    | '/health'
    | '/leaderboards'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/competitions'
    | '/api/health'
    | '/api/plugins'
    | '/api/search'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
    | '/api/admin/competitions'
    | '/api/admin/explorer-poll'
    | '/api/admin/light-poll'
    | '/api/admin/placements'
    | '/api/admin/snapshot'
    | '/api/authors/$authorId'
    | '/api/authors/leaderboard'
    | '/api/health/broken'
    | '/api/health/unverified'
    | '/api/leaderboard/$metric'
    | '/api/leaderboard/trending'
    | '/api/plugins/$id'
    | '/api/stats/breakdown'
    | '/api/stats/categories'
    | '/api/stats/heatmap'
    | '/api/stats/published'
    | '/api/stats/updated'
    | '/api/stats/verified'
    | '/og/plugins/$id'
    | '/api/badges/$stat/$id'
    | '/api/badges/winner/$id'
    | '/api/charts/omagraph/$kind'
    | '/api/badges/ranking/$stat/$id'
    | '/api/charts/author/$login/$metric'
    | '/api/charts/plugin/$id/$metric'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BadgesRoute: typeof BadgesRoute
  CategoriesRoute: typeof CategoriesRoute
  ChartsRoute: typeof ChartsRoute
  CompetitionsRoute: typeof CompetitionsRoute
  HealthRoute: typeof HealthRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCompetitionsRoute: typeof ApiCompetitionsRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiPluginsRoute: typeof ApiPluginsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
  ApiAdminCompetitionsRoute: typeof ApiAdminCompetitionsRoute
  ApiAdminExplorerPollRoute: typeof ApiAdminExplorerPollRoute
  ApiAdminLightPollRoute: typeof ApiAdminLightPollRoute
  ApiAdminPlacementsRoute: typeof ApiAdminPlacementsRoute
  ApiAdminSnapshotRoute: typeof ApiAdminSnapshotRoute
  ApiAuthorsAuthorIdRoute: typeof ApiAuthorsAuthorIdRoute
  ApiAuthorsLeaderboardRoute: typeof ApiAuthorsLeaderboardRoute
  ApiLeaderboardMetricRoute: typeof ApiLeaderboardMetricRoute
  ApiLeaderboardTrendingRoute: typeof ApiLeaderboardTrendingRoute
  ApiStatsBreakdownRoute: typeof ApiStatsBreakdownRoute
  ApiStatsCategoriesRoute: typeof ApiStatsCategoriesRoute
  ApiStatsHeatmapRoute: typeof ApiStatsHeatmapRoute
  ApiStatsPublishedRoute: typeof ApiStatsPublishedRoute
  ApiStatsUpdatedRoute: typeof ApiStatsUpdatedRoute
  ApiStatsVerifiedRoute: typeof ApiStatsVerifiedRoute
  OgPluginsIdRoute: typeof OgPluginsIdRoute
  ApiBadgesStatIdRoute: typeof ApiBadgesStatIdRoute
  ApiBadgesWinnerIdRoute: typeof ApiBadgesWinnerIdRoute
  ApiChartsOmagraphKindRoute: typeof ApiChartsOmagraphKindRoute
  ApiBadgesRankingStatIdRoute: typeof ApiBadgesRankingStatIdRoute
  ApiChartsAuthorLoginMetricRoute: typeof ApiChartsAuthorLoginMetricRoute
  ApiChartsPluginIdMetricRoute: typeof ApiChartsPluginIdMetricRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitions': {
      id: '/api/competitions'
      path: '/api/competitions'
      fullPath: '/api/competitions'
      preLoaderRoute: typeof ApiCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins': {
      id: '/api/plugins'
      path: '/api/plugins'
      fullPath: '/api/plugins'
      preLoaderRoute: typeof ApiPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/competitions': {
      id: '/api/admin/competitions'
      path: '/api/admin/competitions'
      fullPath: '/api/admin/competitions'
      preLoaderRoute: typeof ApiAdminCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/explorer-poll': {
      id: '/api/admin/explorer-poll'
      path: '/api/admin/explorer-poll'
      fullPath: '/api/admin/explorer-poll'
      preLoaderRoute: typeof ApiAdminExplorerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/light-poll': {
      id: '/api/admin/light-poll'
      path: '/api/admin/light-poll'
      fullPath: '/api/admin/light-poll'
      preLoaderRoute: typeof ApiAdminLightPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/placements': {
      id: '/api/admin/placements'
      path: '/api/admin/placements'
      fullPath: '/api/admin/placements'
      preLoaderRoute: typeof ApiAdminPlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/snapshot': {
      id: '/api/admin/snapshot'
      path: '/api/admin/snapshot'
      fullPath: '/api/admin/snapshot'
      preLoaderRoute: typeof ApiAdminSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors/$authorId': {
      id: '/api/authors/$authorId'
      path: '/api/authors/$authorId'
      fullPath: '/api/authors/$authorId'
      preLoaderRoute: typeof ApiAuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors/leaderboard': {
      id: '/api/authors/leaderboard'
      path: '/api/authors/leaderboard'
      fullPath: '/api/authors/leaderboard'
      preLoaderRoute: typeof ApiAuthorsLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/broken': {
      id: '/api/health/broken'
      path: '/broken'
      fullPath: '/api/health/broken'
      preLoaderRoute: typeof ApiHealthBrokenRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/unverified': {
      id: '/api/health/unverified'
      path: '/unverified'
      fullPath: '/api/health/unverified'
      preLoaderRoute: typeof ApiHealthUnverifiedRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/leaderboard/$metric': {
      id: '/api/leaderboard/$metric'
      path: '/api/leaderboard/$metric'
      fullPath: '/api/leaderboard/$metric'
      preLoaderRoute: typeof ApiLeaderboardMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/trending': {
      id: '/api/leaderboard/trending'
      path: '/api/leaderboard/trending'
      fullPath: '/api/leaderboard/trending'
      preLoaderRoute: typeof ApiLeaderboardTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/$id': {
      id: '/api/plugins/$id'
      path: '/$id'
      fullPath: '/api/plugins/$id'
      preLoaderRoute: typeof ApiPluginsIdRouteImport
      parentRoute: typeof ApiPluginsRoute
    }
    '/api/stats/breakdown': {
      id: '/api/stats/breakdown'
      path: '/api/stats/breakdown'
      fullPath: '/api/stats/breakdown'
      preLoaderRoute: typeof ApiStatsBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/categories': {
      id: '/api/stats/categories'
      path: '/api/stats/categories'
      fullPath: '/api/stats/categories'
      preLoaderRoute: typeof ApiStatsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/heatmap': {
      id: '/api/stats/heatmap'
      path: '/api/stats/heatmap'
      fullPath: '/api/stats/heatmap'
      preLoaderRoute: typeof ApiStatsHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/published': {
      id: '/api/stats/published'
      path: '/api/stats/published'
      fullPath: '/api/stats/published'
      preLoaderRoute: typeof ApiStatsPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/updated': {
      id: '/api/stats/updated'
      path: '/api/stats/updated'
      fullPath: '/api/stats/updated'
      preLoaderRoute: typeof ApiStatsUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/verified': {
      id: '/api/stats/verified'
      path: '/api/stats/verified'
      fullPath: '/api/stats/verified'
      preLoaderRoute: typeof ApiStatsVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/plugins/$id': {
      id: '/og/plugins/$id'
      path: '/og/plugins/$id'
      fullPath: '/og/plugins/$id'
      preLoaderRoute: typeof OgPluginsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badges/$stat/$id': {
      id: '/api/badges/$stat/$id'
      path: '/api/badges/$stat/$id'
      fullPath: '/api/badges/$stat/$id'
      preLoaderRoute: typeof ApiBadgesStatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badges/winner/$id': {
      id: '/api/badges/winner/$id'
      path: '/api/badges/winner/$id'
      fullPath: '/api/badges/winner/$id'
      preLoaderRoute: typeof ApiBadgesWinnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/omagraph/$kind': {
      id: '/api/charts/omagraph/$kind'
      path: '/api/charts/omagraph/$kind'
      fullPath: '/api/charts/omagraph/$kind'
      preLoaderRoute: typeof ApiChartsOmagraphKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badges/ranking/$stat/$id': {
      id: '/api/badges/ranking/$stat/$id'
      path: '/api/badges/ranking/$stat/$id'
      fullPath: '/api/badges/ranking/$stat/$id'
      preLoaderRoute: typeof ApiBadgesRankingStatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/author/$login/$metric': {
      id: '/api/charts/author/$login/$metric'
      path: '/api/charts/author/$login/$metric'
      fullPath: '/api/charts/author/$login/$metric'
      preLoaderRoute: typeof ApiChartsAuthorLoginMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/plugin/$id/$metric': {
      id: '/api/charts/plugin/$id/$metric'
      path: '/api/charts/plugin/$id/$metric'
      fullPath: '/api/charts/plugin/$id/$metric'
      preLoaderRoute: typeof ApiChartsPluginIdMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiHealthRouteChildren {
  ApiHealthBrokenRoute: typeof ApiHealthBrokenRoute
  ApiHealthUnverifiedRoute: typeof ApiHealthUnverifiedRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthBrokenRoute: ApiHealthBrokenRoute,
  ApiHealthUnverifiedRoute: ApiHealthUnverifiedRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiPluginsRouteChildren {
  ApiPluginsIdRoute: typeof ApiPluginsIdRoute
}

const ApiPluginsRouteChildren: ApiPluginsRouteChildren = {
  ApiPluginsIdRoute: ApiPluginsIdRoute,
}

const ApiPluginsRouteWithChildren = ApiPluginsRoute._addFileChildren(
  ApiPluginsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApiDocsRoute: ApiDocsRoute,
  BadgesRoute: BadgesRoute,
  CategoriesRoute: CategoriesRoute,
  ChartsRoute: ChartsRoute,
  CompetitionsRoute: CompetitionsRoute,
  HealthRoute: HealthRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCompetitionsRoute: ApiCompetitionsRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiPluginsRoute: ApiPluginsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  PluginsPluginIdRoute: PluginsPluginIdRoute,
  ApiAdminCompetitionsRoute: ApiAdminCompetitionsRoute,
  ApiAdminExplorerPollRoute: ApiAdminExplorerPollRoute,
  ApiAdminLightPollRoute: ApiAdminLightPollRoute,
  ApiAdminPlacementsRoute: ApiAdminPlacementsRoute,
  ApiAdminSnapshotRoute: ApiAdminSnapshotRoute,
  ApiAuthorsAuthorIdRoute: ApiAuthorsAuthorIdRoute,
  ApiAuthorsLeaderboardRoute: ApiAuthorsLeaderboardRoute,
  ApiLeaderboardMetricRoute: ApiLeaderboardMetricRoute,
  ApiLeaderboardTrendingRoute: ApiLeaderboardTrendingRoute,
  ApiStatsBreakdownRoute: ApiStatsBreakdownRoute,
  ApiStatsCategoriesRoute: ApiStatsCategoriesRoute,
  ApiStatsHeatmapRoute: ApiStatsHeatmapRoute,
  ApiStatsPublishedRoute: ApiStatsPublishedRoute,
  ApiStatsUpdatedRoute: ApiStatsUpdatedRoute,
  ApiStatsVerifiedRoute: ApiStatsVerifiedRoute,
  OgPluginsIdRoute: OgPluginsIdRoute,
  ApiBadgesStatIdRoute: ApiBadgesStatIdRoute,
  ApiBadgesWinnerIdRoute: ApiBadgesWinnerIdRoute,
  ApiChartsOmagraphKindRoute: ApiChartsOmagraphKindRoute,
  ApiBadgesRankingStatIdRoute: ApiBadgesRankingStatIdRoute,
  ApiChartsAuthorLoginMetricRoute: ApiChartsAuthorLoginMetricRoute,
  ApiChartsPluginIdMetricRoute: ApiChartsPluginIdMetricRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
